# Generated by Django 4.2.2 on 2023-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(default='default_blog.png', upload_to='images/'),
        ),
    ]
