# Generated by Django 4.2.2 on 2023-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0002_blogcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(default='images/default_blog.png', upload_to='images/'),
        ),
    ]
